# Generated by Django 3.2.4 on 2021-07-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210711_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipments',
            new_name='Shipment',
        ),
    ]
