version: "3.7"
services:
  db:
      image: postgres:11.5      
      environment:
        - POSTGRES_USER=flow
        - POSTGRES_PASSWORD=flow
        - POSTGRES_DB=ecomerce
      expose:
        - 7083
      ports:
        - '7083:5432'
      volumes:
        -  /home/psdata:/var/lib/postgresql/data  